### ISSUE TITLE
[Bug] 标签会因为编辑时图表的resize效果导致不卸载等错误

### ISSUE THREAD

**Issue by xuefei1313** [VisActor/VStory#56]
### Version

1.0.0

### Link to Minimal Reproduction

null

### Steps to Reproduce

1. 使用 Edit
2. 点击一个图表
3. 对图表 resize 

### Current Behavior

![20240822174651_rec_](https://github.com/user-attachments/assets/4a390b0c-b591-4742-b28e-549642e948e2)

### Expected Behavior

绘制正常

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xiaoluoHe** [comment]
问题原因：story 时间线已停止，而图表 label 动画没有关闭，导致没有正确执行；
解决方案：关闭图表标签动画
